"""Sewpat — a Python library for generating sewing patterns."""

from .blocks import BlockConfig, TopBlock, TopBlockBack, TopBlockFront
from .element import GeometryType, PatternElement, PrecisionPoint
from .fitclass import FitClass
from .geometry import (
    Circle,
    CubicBezier,
    Dart,
    DartType,
    InfoBox,
    Line,
    Point,
    Ray,
    Rect,
    Segment,
    Triangle,
    dart_from_edge_at_legs,
    dart_from_edge_at_point,
    dart_from_edge_at_t,
    dart_from_edge_free_tip,
    dart_from_tip_and_legs,
    dart_from_tip_center_width,
    edge_tangent,
    intersect,
    seam_length,
)
from .grids import GridConfig
from .measurements import (
    BlouseMeasurements,
    GarmentConfig,
    HipDistribution,
    TrouserConfig,
    TrouserEase,
    TrouserMeasurements,
    WaistDistribution,
    calculate_hip_distribution,
    calculate_waist_distribution,
    make_measurements_trouser,
    make_top_measurements,
)
from .pages import DinA0, DinA1, DinA2, DinA4
from .pattern import (
    Block,
    ConstructionGrid,
    ConstructionGridPart,
    GarmentPart,
    OverlayPart,
    Pattern,
    PatternPart,
    SeamPairResult,
    SeamPairSpec,
    SeamValidationResult,
    WidthCheckResult,
    WidthLevelSpec,
    WidthValidationResult,
)
from .person import (
    BalanceAdjustments,
    BalancedPerson,
    Gender,
    Person,
    PersonalAdjustments,
    PersonAnalyser,
    load_person,
)
from .style import (
    DEFAULT_STROKE_WIDTH,
    DEFAULT_STROKE_WIDTH_GRAIN,
    STYLE_CENTER_LINE,
    STYLE_CONSTRUCTION_GRID,
    STYLE_CUT,
    STYLE_DART_FOLD,
    STYLE_DART_STITCH,
    STYLE_DEBUG_RED,
    STYLE_FOLD,
    STYLE_GRAINLINE,
    STYLE_HEM,
    STYLE_PRECISION_POINT,
    STYLE_SEAM_ALLOWANCE,
    STYLE_STITCH,
    STYLE_STITCH_BEVEL,
    STYLE_WAISTBAND,
    Marker,
    StyleOptions,
)
from .units import CM, INCH, MM

__all__ = [
    # Geometry primitives
    "Point",
    "Segment",
    "Ray",
    "Circle",
    "Line",
    "Rect",
    "Triangle",
    "CubicBezier",
    "Dart",
    "DartType",
    "InfoBox",
    # Dart factory free functions
    "dart_from_tip_center_width",
    "dart_from_edge_at_legs",
    "dart_from_tip_and_legs",
    "dart_from_edge_at_t",
    "dart_from_edge_at_point",
    "dart_from_edge_free_tip",
    # Geometry helpers
    "edge_tangent",
    "intersect",
    "seam_length",
    # Units
    "MM",
    "CM",
    "INCH",
    # Grids & Blocks
    "BlockConfig",
    "GridConfig",
    "TopBlock",
    "TopBlockBack",
    "TopBlockFront",
    # Pattern element
    "GeometryType",
    "PatternElement",
    "PrecisionPoint",
    # Pattern
    "PatternPart",
    "Pattern",
    "GarmentPart",
    "ConstructionGrid",
    "ConstructionGridPart",
    "Block",
    "OverlayPart",
    "SeamPairSpec",
    "SeamPairResult",
    "SeamValidationResult",
    "WidthLevelSpec",
    "WidthCheckResult",
    "WidthValidationResult",
    # Pages
    "DinA4",
    "DinA2",
    "DinA1",
    "DinA0",
    # Measurements
    "BlouseMeasurements",
    "TrouserMeasurements",
    "TrouserEase",
    "GarmentConfig",
    "TrouserConfig",
    "HipDistribution",
    "WaistDistribution",
    "FitClass",
    "make_top_measurements",
    "make_measurements_trouser",
    "calculate_hip_distribution",
    "calculate_waist_distribution",
    # Person
    "Person",
    "BalancedPerson",
    "Gender",
    "BalanceAdjustments",
    "PersonalAdjustments",
    "PersonAnalyser",
    "load_person",
    # Style
    "StyleOptions",
    "Marker",
    "DEFAULT_STROKE_WIDTH",
    "DEFAULT_STROKE_WIDTH_GRAIN",
    "STYLE_GRAINLINE",
    "STYLE_FOLD",
    "STYLE_HEM",
    "STYLE_STITCH",
    "STYLE_STITCH_BEVEL",
    "STYLE_CUT",
    "STYLE_WAISTBAND",
    "STYLE_CENTER_LINE",
    "STYLE_SEAM_ALLOWANCE",
    "STYLE_CONSTRUCTION_GRID",
    "STYLE_DEBUG_RED",
    "STYLE_DART_STITCH",
    "STYLE_DART_FOLD",
    "STYLE_PRECISION_POINT",
]
