"""PatternElement — a geometric shape with a style and metadata flags."""

from .geometry import (
    Circle,
    CubicBezier,
    Dart,
    InfoBox,
    Line,
    Point,
    Ray,
    Rect,
    Segment,
    Triangle,
)
from .style import STYLE_CONSTRUCTION_GRID, STYLE_PRECISION_POINT, StyleOptions
from .units import MM


class PatternElement:
    """A geometric shape with a style and metadata flags.

    Attributes:
        geometry: The shape (Point, Segment, Rect, Circle, CubicBezier, …).
        style: Visual style.
        name: Label override; falls back to ``geometry.name``.
        role: Optional semantic tag (e.g. ``"dart_stitch"``, ``"dart_fold"``).
            Used to filter elements by purpose after construction.
        is_outline: Participates in seam-allowance generation.
        is_seam_allowance: Generated by :meth:`~sewpat.pattern.PatternPart.add_seam_allowance`.
        is_seam_notch: Seam-line copy of a notch; hidden when SA is shown.
        is_construction: Drafting/construction aid. Hidden when
            ``show_construction=False`` is passed to the export functions.
            Use this for auxiliary lines, original construction segments,
            and any element that should not appear on the final print.
    """

    def __init__(
        self,
        geometry: Segment
        | Rect
        | Circle
        | Triangle
        | CubicBezier
        | Line
        | Ray
        | Point
        | InfoBox
        | Dart,
        style: StyleOptions | None = None,
        name: str | None = None,
        role: str | None = None,
        is_outline: bool = False,
        is_seam_allowance: bool = False,
        is_construction: bool = False,
    ) -> None:
        self.geometry = geometry
        if style is None and is_construction:
            self.style = STYLE_CONSTRUCTION_GRID
        else:
            self.style = style if style is not None else StyleOptions()
        self.name = name
        self.role = role
        self.is_outline = is_outline
        self.is_seam_allowance = is_seam_allowance
        self.is_seam_notch: bool = False
        self.is_construction: bool = is_construction

    def get_name(self) -> str | None:
        """Return the effective name (element name overrides geometry name)."""
        if self.name is not None:
            return self.name
        return getattr(self.geometry, "name", None)


class PrecisionPoint:
    """A two-circle precision mark placed at a single centre point.

    Encapsulates the two concentric circles (outer and inner) used on sewing
    patterns to mark precise placement points such as dart tips or notch
    pivots.  Both circles share the same style — either the explicitly supplied
    *style* or :data:`~sewpat.style.STYLE_PRECISION_POINT` as the default.

    Args:
        center: The point at which to place the precision mark.
        outer_radius: Radius of the outer circle in mm. Defaults to 2 mm.
        inner_radius: Radius of the inner circle in mm. Defaults to 0.2 mm.
        style: Visual style for both circles. Defaults to
            :data:`~sewpat.style.STYLE_PRECISION_POINT`.
    """

    def __init__(
        self,
        center: Point,
        outer_radius: float = 2.0 * MM,
        inner_radius: float = 0.2 * MM,
        style: StyleOptions | None = None,
    ) -> None:
        self.center = center
        self.outer_radius = outer_radius
        self.inner_radius = inner_radius
        self.style = style if style is not None else STYLE_PRECISION_POINT

    def build_elements(self) -> list[PatternElement]:
        """Return the two :class:`PatternElement` circles for this precision mark.

        Returns:
            A list of two ``PatternElement`` objects: outer circle first,
            inner circle second.
        """
        return [
            PatternElement(
                Circle(self.center, radius=self.outer_radius), style=self.style
            ),
            PatternElement(
                Circle(self.center, radius=self.inner_radius), style=self.style
            ),
        ]
