"""PatternElement — a geometric shape with a style and metadata flags."""

from .geometry import (
    Circle,
    CubicBezier,
    Dart,
    InfoBox,
    Line,
    Point,
    Ray,
    Rect,
    Segment,
    Triangle,
)
from .style import STYLE_CONSTRUCTION_GRID, STYLE_PRECISION_POINT, StyleOptions
from .units import MM

#: Union of all geometry types accepted by :class:`PatternElement`.
type GeometryType = (
    Segment | Rect | Circle | Triangle | CubicBezier | Line | Ray | Point | InfoBox | Dart
)


class PatternElement:
    """A geometric shape with a style and metadata flags.

    Attributes:
        geometry: The shape (Point, Segment, Rect, Circle, CubicBezier, …).
        style: Visual style.
        name: Label override; falls back to ``geometry.name``.
        role: Optional semantic tag (e.g. ``"dart_stitch"``, ``"dart_fold"``).
            Used to filter elements by purpose after construction.
        is_outline: Participates in seam-allowance generation.
        is_seam_allowance: Generated by
            :meth:`~sewpat.pattern.PatternPart.add_seam_allowance`.
        is_seam_notch: Seam-line copy of a notch; hidden when SA is shown.
        is_construction: Drafting/construction aid. Hidden when
            ``show_construction=False`` is passed to the export functions.
            Use this for auxiliary lines, original construction segments,
            and any element that should not appear on the final print.
    """

    def __init__(
        self,
        geometry: GeometryType,
        style: StyleOptions | None = None,
        name: str | None = None,
        role: str | None = None,
        is_outline: bool = False,
        is_seam_allowance: bool = False,
        is_construction: bool = False,
    ) -> None:
        """Wrap *geometry* in a styled, flagged pattern element."""
        self.geometry = geometry
        if style is None and is_construction:
            self.style = STYLE_CONSTRUCTION_GRID
        else:
            self.style = style if style is not None else StyleOptions()
        self.name = name
        self.role = role
        self.is_outline = is_outline
        self.is_seam_allowance = is_seam_allowance
        self.is_seam_notch: bool = False
        self.is_construction: bool = is_construction
        # Internal: outward-direction reference for SA offset computation.
        # None → use the part centroid (default for all elements).
        # Set to dart.tip by add_dart() for roof segments so the offset always
        # goes away from the tip, which is the physically correct direction
        # regardless of where the centroid is relative to the roof geometry.
        self._sa_center: object | None = None
        # Internal: set by add_dart() on dart-center/leg notch elements so that
        # _project_dart_notches_to_sa() can access the parent Dart and leg point.
        self._dart_ref: Dart | None = None
        self._leg_pt: Point | None = None

    def get_name(self) -> str | None:
        """Return the effective name (element name overrides geometry name)."""
        if self.name is not None:
            return self.name
        return getattr(self.geometry, "name", None)

    def split_at_dart(self, dart: Dart) -> list[PatternElement]:
        """Split this element's geometry at both dart legs and return new elements.

        This is the standard pattern-making operation of *removing the dart
        mouth from a seam edge*: the section of the edge between
        ``dart.leg_a`` and ``dart.leg_b`` is discarded, while the parts
        outside the dart mouth become new :class:`PatternElement` objects
        that inherit **all** properties of ``self`` — style, ``is_outline``,
        ``is_construction``, ``is_seam_allowance``, ``role``, and ``name``.

        Only :class:`~sewpat.geometry.Segment` and
        :class:`~sewpat.geometry.CubicBezier` geometries support this
        operation (they are the only types with ``split_at_points``).
        All other geometry types raise :class:`TypeError`.

        Use this together with :meth:`~sewpat.pattern.PatternPart.append_split_at_dart`
        to append the outer segments directly onto a part::

            sleeve_elem = PatternElement(
                sleeve_back.set_name("Sleeve Back"),
                style=STYLE_STITCH, is_outline=True,
            )
            block_back.append_split_at_dart(sleeve_elem, shoulder_dart_back)

        Args:
            dart: :class:`~sewpat.geometry.Dart` whose ``leg_a`` / ``leg_b``
                define the mouth cut points.

        Returns:
            List of new :class:`PatternElement` objects for the sub-segments
            that lie **outside** the dart mouth, in curve order.

        Raises:
            TypeError: When the geometry does not support ``split_at_points``
                (e.g. :class:`~sewpat.geometry.Rect`,
                :class:`~sewpat.geometry.Circle`).
        """
        import copy

        geom = self.geometry
        if not isinstance(geom, (Segment, CubicBezier)):
            raise TypeError(
                f"split_at_dart requires a Segment or CubicBezier geometry, "
                f"got {type(geom).__name__!r}"
            )

        all_subs = geom.split_at_points([dart.leg_a, dart.leg_b])

        # With two split points the dart mouth is the middle sub-segment (index 1).
        # When a leg coincides with an endpoint fewer pieces are returned — keep all.
        outer_subs = all_subs[:1] + all_subs[2:] if len(all_subs) >= 3 else all_subs

        result: list[PatternElement] = []
        for sub in outer_subs:
            if geom.name and hasattr(sub, "set_name"):
                sub = sub.set_name(geom.name)
            child = PatternElement(
                geometry=sub,
                style=copy.copy(self.style),
                name=self.name,
                role=self.role,
                is_outline=self.is_outline,
                is_seam_allowance=self.is_seam_allowance,
                is_construction=self.is_construction,
            )
            child.is_seam_notch = self.is_seam_notch
            result.append(child)
        return result


class PrecisionPoint:
    """A two-circle precision mark placed at a single centre point.

    Encapsulates the two concentric circles (outer and inner) used on sewing
    patterns to mark precise placement points such as dart tips or notch
    pivots.  Both circles share the same style — either the explicitly supplied
    *style* or :data:`~sewpat.style.STYLE_PRECISION_POINT` as the default.

    Args:
        center: The point at which to place the precision mark.
        outer_radius: Radius of the outer circle in mm. Defaults to 5 mm.
        inner_radius: Radius of the inner circle in mm. Defaults to 0.5 mm.
        style: Visual style for both circles. Defaults to
            :data:`~sewpat.style.STYLE_PRECISION_POINT`.
    """

    def __init__(
        self,
        center: Point,
        outer_radius: float = 5.0 * MM,
        inner_radius: float = 0.5 * MM,
        style: StyleOptions | None = None,
    ) -> None:
        """Initialise with *center*, radii, and optional style override."""
        self.center = center
        self.outer_radius = outer_radius
        self.inner_radius = inner_radius
        self.style = style if style is not None else STYLE_PRECISION_POINT

    def build_elements(self) -> list[PatternElement]:
        """Return the two :class:`PatternElement` circles for this precision mark.

        Returns:
            A list of two ``PatternElement`` objects: outer circle first,
            inner circle second.
        """
        return [
            PatternElement(Circle(self.center, radius=self.outer_radius), style=self.style),
            PatternElement(Circle(self.center, radius=self.inner_radius), style=self.style),
        ]
