"""PatternElement — a geometric shape with a style and metadata flags."""

from .geometry import (
    Circle,
    CubicBezier,
    InfoBox,
    Point,
    Rect,
    Segment,
    Triangle,
)
from .style import StyleOptions


class PatternElement:
    """A geometric shape with a style and metadata flags.

    Attributes:
        geometry: The shape (Point, Segment, Rect, Circle, CubicBezier, …).
        style: Visual style.
        name: Label override; falls back to ``geometry.name``.
        is_outline: Participates in seam-allowance generation.
        is_seam_allowance: Generated by :meth:`~sewpat.pattern.PatternPart.add_seam_allowance`.
        is_seam_notch: Seam-line copy of a notch; hidden when SA is shown.
        is_construction: Belongs to a construction-grid layer (show/hide via render flag).
    """

    def __init__(
        self,
        geometry: Segment | Rect | Circle | Triangle | CubicBezier | Point | InfoBox,
        style: StyleOptions | None = None,
        name: str | None = None,
        is_outline: bool = False,
        is_seam_allowance: bool = False,
        is_construction: bool = False,
    ) -> None:
        self.geometry = geometry
        self.style = style if style is not None else StyleOptions()
        self.name = name
        self.is_outline = is_outline
        self.is_seam_allowance = is_seam_allowance
        self.is_seam_notch: bool = False
        self.is_construction: bool = is_construction

    def get_name(self) -> str | None:
        """Return the effective name (element name overrides geometry name)."""
        if self.name is not None:
            return self.name
        return getattr(self.geometry, "name", None)

