import math
import shapely.geometry as _sg
import shapely.ops as _so

from .style import StyleOptions, STYLE_GRAINLINE, STYLE_SEAM_ALLOWANCE
from .geometry import (
    Rect,
    Point,
    Segment,
    Circle,
    Triangle,
    InfoBox,
    CubicBezier,
    geom_start,
    geom_end,
    geom_to_shapely,
    with_endpoints,
    build_chain,
    buffer_chain,
    miter_corner,
    round_corner,
    outline_polygon,
    offset_adaptive as _offset_adaptive,
    seam_length as _geom_seam_length,
)
from .units import CM, MM


class PatternElement:
    """A geometric shape combined with a style and metadata flags.

    Attributes:
        geometry: The shape (Point, Segment, Rect, Circle, CubicBezier, …).
        style: Visual style for rendering.
        name: Optional label override; falls back to ``geometry.name``.
        is_outline: Participates in seam-allowance generation.
        is_seam_allowance: Generated by :meth:`PatternPart.add_seam_allowance`.
        is_seam_notch: Seam-line copy of a notch; hidden when SA is shown.
    """

    def __init__(
        self,
        geometry: Segment | Rect | Circle | Triangle | CubicBezier | Point | InfoBox,
        style: StyleOptions | None = None,
        name: str | None = None,
        is_outline: bool = False,
        is_seam_allowance: bool = False,
    ) -> None:
        self.geometry = geometry
        self.style = style if style is not None else StyleOptions()
        self.name = name
        self.is_outline = is_outline
        self.is_seam_allowance = is_seam_allowance
        self.is_seam_notch: bool = False

    def get_name(self) -> str | None:
        """Return the effective name (element name overrides geometry name)."""
        if self.name is not None:
            return self.name
        return getattr(self.geometry, "name", None)


class PatternPart:
    """A collection of pattern elements forming one pattern piece."""

    def __init__(self, name: str, elements: list[PatternElement] | None = None) -> None:
        self.name = name
        self.elements: list[PatternElement] = elements if elements is not None else []

    def append(
        self,
        geometry: object,
        style: StyleOptions | None = None,
        name: str | None = None,
        is_outline: bool = False,
    ) -> PatternElement:
        """Wrap *geometry* in a PatternElement and append it to this part.

        Returns the newly created PatternElement.
        """
        elem = PatternElement(
            geometry=geometry, style=style, name=name, is_outline=is_outline
        )
        self.elements.append(elem)
        return elem

    def extend(self, elements: list[PatternElement]) -> None:
        """Append multiple PatternElements at once."""
        self.elements.extend(elements)

    def _outline_polygon(self):
        """Build a Shapely Polygon from the ``is_outline`` elements of this part."""
        geoms = [
            e.geometry
            for e in self.elements
            if e.is_outline and isinstance(e.geometry, (Segment, CubicBezier))
        ]
        return outline_polygon(geoms) if geoms else None

    @property
    def centroid(self) -> Point | None:
        """Geometric centroid of the outline polygon, or ``None`` if not yet defined."""
        poly = self._outline_polygon()
        if poly is None or poly.is_empty:
            return None
        c = poly.centroid
        return Point(c.x, c.y)

    @property
    def area_cm2(self) -> float | None:
        """Area of the outline polygon in cm², or ``None`` if not yet defined."""
        poly = self._outline_polygon()
        if poly is None or poly.is_empty:
            return None
        return poly.area / 100.0

    def bounding_box(self) -> tuple[Point, Point] | None:
        """Axis-aligned bounding box of the outline polygon.

        Returns:
            ``(min_point, max_point)`` in mm, or ``None`` if no outline exists.
        """
        poly = self._outline_polygon()
        if poly is None or poly.is_empty:
            return None
        minx, miny, maxx, maxy = poly.bounds
        return Point(minx, miny), Point(maxx, maxy)

    def seam_length(
        self,
        geoms_or_names: list[Segment | CubicBezier | PatternElement | str],
    ) -> float:
        """Return the total arc length in mm of the given seam elements.

        Each entry may be a ``Segment``, ``CubicBezier``, ``PatternElement``
        (geometry is unwrapped), or a ``str`` name (all matching elements
        in this part are summed).  Mixed lists are fine.

        Raises:
            KeyError: If a name string matches no element in this part.
            TypeError: If an entry is none of the accepted types.
        """
        resolved: list[Segment | CubicBezier] = []
        for item in geoms_or_names:
            if isinstance(item, PatternElement):
                if isinstance(item.geometry, (Segment, CubicBezier)):
                    resolved.append(item.geometry)
            elif isinstance(item, (Segment, CubicBezier)):
                resolved.append(item)
            elif isinstance(item, str):
                matches = [
                    e.geometry
                    for e in self.elements
                    if e.get_name() == item
                    and isinstance(e.geometry, (Segment, CubicBezier))
                ]
                if not matches:
                    raise KeyError(
                        f"No Segment/CubicBezier named {item!r} in part {self.name!r}"
                    )
                resolved.extend(matches)
            else:
                raise TypeError(
                    f"Expected Segment, CubicBezier, PatternElement, or str; got {type(item).__name__}"
                )
        return _geom_seam_length(resolved)

    def contains_point(self, point: Point) -> bool:
        """Return True if *point* lies strictly inside the outline polygon (boundary = False)."""
        poly = self._outline_polygon()
        if poly is None or poly.is_empty:
            return False
        return bool(poly.contains(_sg.Point(point.x, point.y)))

    def _nudge_point_inside(
        self,
        point: Point,
        inward_ref: Point,
        step: float = 1.0,
        max_steps: int = 200,
    ) -> Point:
        """Walk *point* toward *inward_ref* until it lies inside (or on) the outline.

        Points already inside, on the boundary, or within 0.1 mm of it (Bézier
        discretisation tolerance) are returned unchanged.  The walk always stays
        on the *point* → *inward_ref* axis so the caller controls the direction.
        """
        if self.contains_point(point):
            return point

        poly = self._outline_polygon()
        if poly is None or poly.is_empty:
            return point

        dx = inward_ref.x - point.x
        dy = inward_ref.y - point.y
        dist = (dx**2 + dy**2) ** 0.5
        if dist < 1e-9:
            return point
        ux, uy = dx / dist, dy / dist

        # 0.1 mm buffer absorbs Bézier-to-polyline discretisation rounding.
        buffered = poly.buffer(0.1)

        def _inside(p: Point) -> bool:
            return bool(buffered.contains(_sg.Point(p.x, p.y)))

        if _inside(point):
            return point

        steps = max(max_steps, math.ceil(dist / step) + 1)
        for i in range(1, steps + 1):
            candidate = Point(point.x + ux * step * i, point.y + uy * step * i)
            if _inside(candidate):
                return candidate

        return point

    def add_grainline(
        self,
        start: Point,
        end: Point,
        name: str = "grainline / Fadenlauf",
    ) -> PatternElement:
        """Add a grainline segment, nudging outside endpoints inward along the grain axis.

        Each endpoint is nudged toward the opposite one, so the grainline stays
        perfectly straight even when an endpoint sits on the outline boundary.
        """
        start = self._nudge_point_inside(start, end)
        end = self._nudge_point_inside(end, start)
        return self.append(Segment(start, end, name=name), style=STYLE_GRAINLINE)

    def add_info_box(
        self, header: str | None = None, notes: list[str] | None = None
    ) -> PatternElement | None:
        """Add an info box at the centroid of this part.

        Args:
            header: Bold header text. Defaults to the part name.
            notes: Optional note lines shown below the header.

        Returns:
            The created PatternElement, or ``None`` if no centroid exists yet.
        """
        pos = self.centroid
        if pos is None:
            return None
        return self.append(
            InfoBox(
                position=pos.translate(0, 3 * CM),
                header=header if header is not None else self.name,
                notes=notes,
            )
        )

    def add_precision_points(self, *centers: Point) -> None:
        """Add a two-circle precision mark at each given point."""
        for center in centers:
            self.append(Circle(center, radius=2 * MM))
            self.append(Circle(center, radius=0.2 * MM))

    def add_notches(
        self,
        *points: Point,
        seam_edge: Segment | CubicBezier | None = None,
        length: float = 0.8 * CM,
        width: float = 0.4 * CM,
        is_back: bool = False,
    ) -> None:
        """Add filled-triangle notch marks at *points*, always pointing inward.

        Args:
            *points: Reference points for the notches.
            seam_edge: Edge to project onto and derive tangent/normal from.
                Without it a vertical triangle centred on the point is used.
            length: Tip-to-base distance. Defaults to 0.8 cm.
            width: Base width on the seam edge. Defaults to 0.4 cm.
            is_back: Two neighbouring triangles (back piece convention) if True.

        When SA elements are already present (i.e. :meth:`add_seam_allowance`
        was called first), a second triangle is projected onto the cut edge and
        the seam-line copy is flagged ``is_seam_notch`` so rendering can hide it.
        """
        inward_ref = self.centroid
        half_w = width / 2
        gap = width * 0.5

        sa_geoms: list[Segment | CubicBezier] = [
            e.geometry
            for e in self.elements
            if e.is_seam_allowance and isinstance(e.geometry, (Segment, CubicBezier))
        ]

        def _project(edge: Segment | CubicBezier, ref: Point) -> tuple:
            if isinstance(edge, Segment):
                notch_pt = edge.project_point(ref)
                along = edge.unit_direction
                normal = edge.unit_normal
            else:
                _, nearest = _so.nearest_points(
                    _sg.Point(ref.x, ref.y), geom_to_shapely(edge)
                )
                notch_pt = Point(nearest.x, nearest.y)
                t_c = (
                    min(
                        range(65),
                        key=lambda k: edge.point_at_t(k / 64).distance_to(notch_pt),
                    )
                    / 64
                )
                tangent = edge.tangent_at_t(t_c)
                tang_len = float((tangent[0] ** 2 + tangent[1] ** 2) ** 0.5)
                along = tangent / tang_len if tang_len > 1e-12 else tangent
                normal = edge.normal_at_t(t_c)
            if inward_ref is not None:
                dot = normal[0] * (inward_ref.x - notch_pt.x) + normal[1] * (
                    inward_ref.y - notch_pt.y
                )
                if dot < 0:
                    normal = -normal
            return notch_pt, along, normal

        def _closest_sa_edge(ref: Point) -> Segment | CubicBezier | None:
            best_edge, best_dist = None, float("inf")
            sp = _sg.Point(ref.x, ref.y)
            for g in sa_geoms:
                d = sp.distance(geom_to_shapely(g))
                if d < best_dist:
                    best_dist, best_edge = d, g
            return best_edge

        def _place_triangles(notch_pt: Point, along, normal, is_sa: bool) -> list:
            ax, ay = float(along[0]), float(along[1])
            nx, ny = float(normal[0]), float(normal[1])
            offsets = (
                [0.0] if not is_back else [-(half_w + gap / 2), +(half_w + gap / 2)]
            )
            created = []
            for offset in offsets:
                centre = notch_pt.translate(offset * ax, offset * ay)
                bl = centre.translate(-half_w * ax, -half_w * ay)
                br = centre.translate(half_w * ax, half_w * ay)
                tip = centre.translate(nx * length, ny * length)
                elem = self.append(Triangle(bl, br, tip))
                elem.is_seam_allowance = is_sa
                created.append(elem)
            return created

        for pt in points:
            if seam_edge is not None:
                notch_pt, along, normal = _project(seam_edge, pt)
            else:
                notch_pt, along, normal = pt, (1.0, 0.0), (0.0, -1.0)
            seam_elems = _place_triangles(notch_pt, along, normal, is_sa=False)

            if sa_geoms:
                sa_edge = _closest_sa_edge(notch_pt)
                if sa_edge is not None:
                    sa_notch_pt, sa_along, sa_normal = _project(sa_edge, notch_pt)
                    _place_triangles(sa_notch_pt, sa_along, sa_normal, is_sa=True)
                    for e in seam_elems:
                        e.is_seam_notch = True

    def add_seam_allowance(
        self,
        distance: float,
        outline_elements: list[PatternElement] | None = None,
        style: StyleOptions | None = None,
        corner_join: str = "miter",
    ) -> list[PatternElement]:
        """Offset the outline outward by *distance* mm and add the result as SA elements.

        Three code paths:
        - **Rect** outlines are expanded uniformly.
        - **Pure-segment** outlines (no Béziers, no per-element overrides) use
          ``Shapely.Polygon.buffer()`` — fast and concave-safe.
        - **Mixed / Bézier** outlines offset each element individually and stitch
          corners according to *corner_join*.

        Corner join and distance can be overridden per-element via
        ``StyleOptions(corner_join=…, seam_allowance=…)`` on any outline element;
        per-element values take priority over the arguments here.

        Args:
            distance: Seam allowance in mm (must be positive).
            outline_elements: Defaults to all ``is_outline`` elements.
            style: Style for the generated elements. Defaults to ``STYLE_SEAM_ALLOWANCE``.
            corner_join: ``"miter"`` (default), ``"round"``, or ``"bevel"``.

        Returns:
            List of newly created PatternElement objects.
        """
        _CJ = {"miter": 2, "round": 1, "bevel": 3}
        if corner_join not in _CJ:
            raise ValueError(
                f"corner_join must be one of {list(_CJ)!r}, got {corner_join!r}"
            )
        if distance <= 0:
            raise ValueError(
                f"seam allowance distance must be positive, got {distance}"
            )

        sa_style = style if style is not None else STYLE_SEAM_ALLOWANCE

        if outline_elements is None:
            outline_elements = [e for e in self.elements if e.is_outline]
        if not outline_elements:
            return []

        # ── Rect fast-path ────────────────────────────────────────────────────
        for elem in outline_elements:
            if isinstance(elem.geometry, Rect):
                g = elem.geometry
                new_elem = self.append(
                    Rect(
                        origin=g.origin.translate(-distance, -distance),
                        width=g.width + 2 * distance,
                        height=g.height + 2 * distance,
                        name=g.name,
                    ),
                    style=sa_style,
                )
                new_elem.is_seam_allowance = True
                return [new_elem]

        geoms: list[Segment | CubicBezier] = [
            e.geometry
            for e in outline_elements
            if isinstance(e.geometry, (Segment, CubicBezier))
        ]

        # ── Pure-segment path: Shapely buffer ────────────────────────────────
        has_per_elem_sa = any(
            getattr(e.style, "seam_allowance", 0.0) > 0
            for e in outline_elements
            if isinstance(e.geometry, (Segment, CubicBezier))
        )
        has_per_elem_cj = any(
            getattr(e.style, "corner_join", None) is not None
            for e in outline_elements
            if isinstance(e.geometry, (Segment, CubicBezier))
        )
        if (
            not any(isinstance(g, CubicBezier) for g in geoms)
            and not has_per_elem_sa
            and not has_per_elem_cj
        ):
            chain = build_chain(geoms)
            buf_coords = buffer_chain(chain, distance, join_style=_CJ[corner_join])
            added: list[PatternElement] = []
            for (x1, y1), (x2, y2) in zip(buf_coords, buf_coords[1:]):
                elem = self.append(
                    Segment(Point(x1, y1), Point(x2, y2)), style=sa_style
                )
                elem.is_seam_allowance = True
                added.append(elem)
            return added

        # ── Mixed / Bézier path: per-element offset + corner stitching ────────
        center = self.centroid
        chain_mixed = build_chain(geoms)

        def _ep_key(g: Segment | CubicBezier) -> frozenset:
            s, e = geom_start(g), geom_end(g)
            return frozenset(
                [(round(s.x, 6), round(s.y, 6)), (round(e.x, 6), round(e.y, 6))]
            )

        elem_sa: dict[frozenset, float] = {
            _ep_key(e.geometry): getattr(e.style, "seam_allowance", 0.0)
            for e in outline_elements
            if isinstance(e.geometry, (Segment, CubicBezier))
            and getattr(e.style, "seam_allowance", 0.0) > 0
        }

        _valid_cj = {"miter", "round", "bevel"}
        elem_cj: dict[frozenset, str] = {}
        for e in outline_elements:
            if not isinstance(e.geometry, (Segment, CubicBezier)):
                continue
            val = getattr(e.style, "corner_join", None)
            if val is None:
                continue
            if val not in _valid_cj:
                raise ValueError(
                    f"StyleOptions.corner_join must be one of {sorted(_valid_cj)!r}, "
                    f"got {val!r} on element {e.get_name()!r}"
                )
            elem_cj[_ep_key(e.geometry)] = val

        offset_groups: list[list[Segment | CubicBezier]] = [
            _offset_adaptive(g, elem_sa.get(_ep_key(g), distance), center)
            for g in chain_mixed
        ]

        n = len(offset_groups)
        arc_inserts: list[tuple[int, CubicBezier]] = []
        for i in range(n):
            j = (i + 1) % n
            ga = offset_groups[i][-1]
            gb = offset_groups[j][0]
            if geom_end(ga).distance_to(geom_start(gb)) > 0.01:
                key_a = _ep_key(chain_mixed[i])
                key_b = _ep_key(chain_mixed[j])
                effective_cj = elem_cj.get(key_a) or elem_cj.get(key_b) or corner_join

                if effective_cj == "miter":
                    corner = miter_corner(ga, gb, distance)
                    offset_groups[i][-1] = with_endpoints(ga, geom_start(ga), corner)
                    offset_groups[j][0] = with_endpoints(gb, corner, geom_end(gb))
                elif effective_cj == "round":
                    arc = round_corner(ga, gb)
                    if isinstance(arc, CubicBezier):
                        offset_groups[i][-1] = with_endpoints(
                            ga, geom_start(ga), arc.p0
                        )
                        offset_groups[j][0] = with_endpoints(gb, arc.p3, geom_end(gb))
                        arc_inserts.append((i, arc))
                    else:
                        offset_groups[i][-1] = with_endpoints(ga, geom_start(ga), arc)
                        offset_groups[j][0] = with_endpoints(gb, arc, geom_end(gb))
                else:  # bevel
                    _ea = geom_end(ga)
                    _sb = geom_start(gb)
                    corner = Point(*(0.5 * (_ea.coords + _sb.coords)))
                    offset_groups[i][-1] = with_endpoints(ga, geom_start(ga), corner)
                    offset_groups[j][0] = with_endpoints(gb, corner, geom_end(gb))

        flat: list[Segment | CubicBezier] = []
        for group in offset_groups:
            flat.extend(group)
        group_end_flat: list[int] = []
        pos = 0
        for group in offset_groups:
            pos += len(group)
            group_end_flat.append(pos - 1)
        for group_i, arc in sorted(arc_inserts, key=lambda x: x[0], reverse=True):
            flat.insert(group_end_flat[group_i] + 1, arc)

        added_mixed: list[PatternElement] = []
        for geom in flat:
            elem = self.append(geom, style=sa_style)
            elem.is_seam_allowance = True
            added_mixed.append(elem)
        return added_mixed


class Pattern:
    """A complete sewing pattern consisting of one or more pattern parts.

    Attributes:
        name: Pattern name.
        parts: Ordered list of PatternPart objects.
        anchor: Top-left origin on the page. Defaults to (1.5 cm, 1.5 cm).
        reference_square: Optional scale-verification square added via
            :meth:`add_reference_square`.
    """

    def __init__(
        self,
        name: str,
        parts: list[PatternPart] | None = None,
        anchor: Point | None = None,
    ) -> None:
        self.name = name
        self.parts: list[PatternPart] = parts if parts is not None else []
        self.reference_square: PatternElement | None = None
        self.anchor: Point = anchor if anchor is not None else Point(1.5 * CM, 1.5 * CM)

    def add_reference_square(
        self,
        origin: Point,
        edge_length: float = 3 * CM,
        style: StyleOptions | None = None,
        part: PatternPart | None = None,
    ) -> PatternElement:
        """Add a print-scale verification square to the pattern.

        If *part* is given (or the pattern has exactly one part) and *origin*
        falls outside the bounding box, the square is clamped inside with 2 mm
        padding.

        Args:
            origin: Preferred top-left corner.
            edge_length: Side length. Defaults to 3 cm.
            style: Defaults to ``StyleOptions(stroke_width=DEFAULT_STROKE_WIDTH)``.
            part: Part used for boundary clamping. Auto-detected for single-part patterns.

        Returns:
            The created PatternElement (also stored in ``self.reference_square``).
        """
        from .style import DEFAULT_STROKE_WIDTH

        target_part: PatternPart | None = part
        if target_part is None and len(self.parts) == 1:
            target_part = self.parts[0]

        final_origin = origin
        if target_part is not None:
            bb = target_part.bounding_box()
            if bb is not None:
                mn, mx = bb
                pad = 2 * MM
                ox = max(mn.x + pad, min(origin.x, mx.x - edge_length - pad))
                oy = max(mn.y + pad, min(origin.y, mx.y - edge_length - pad))
                final_origin = Point(ox, oy)

        elem = PatternElement(
            geometry=Rect(
                origin=final_origin,
                width=edge_length,
                height=edge_length,
                name=f"{edge_length / CM:.0f}cm × {edge_length / CM:.0f}cm",
            ),
            style=(
                style
                if style is not None
                else StyleOptions(stroke_width=DEFAULT_STROKE_WIDTH)
            ),
        )
        self.reference_square = elem
        return elem

    def add_part(self, part: PatternPart) -> PatternPart:
        """Append *part* to this pattern and return it (for chaining)."""
        self.parts.append(part)
        return part

    def get_part(self, name: str) -> PatternPart:
        """Return the first PatternPart with the given name.


        Raises:
            KeyError: If no part with that name exists.
        """
        for part in self.parts:
            if part.name == name:
                return part
        raise KeyError(f"No PatternPart named {name!r}")
